### ISSUE TITLE
proxy port

### ISSUE THREAD

**Issue by roydekleijn** [QAutomatron/docker-browsermob-proxy#1]
Hi, using docker-compose, how can we link specific ports ?

What I have now:

app-rest:
  build: ./application
  links:
    - proxy
  ports:
    - "8080:8080"
proxy:
  image: qautomatron/docker-browsermob-proxy:latest
  ports:
    - "9090:9090"
    - "39500-39999:39500:39999"

you can access the rest application via http://192.168.99.100:8080

How can I limit bandwidth for these requests ?

http://localhost:9090/proxy/<which port to set>/limit

Thanks in advance

**Comment by QAutomatron** [comment]
Hello.

To limit bandwidth you should use (according to BMP documentation):
`http://localhost:9090/proxy/[port-number]/limit`

But before this you should create a proxy on port. 
For example, by send a POST request on:
`http://localhost:9090/proxy`
In response you get a proxy on port from 39500 to 39999 (this is default setting, you could change it by passing ENV value). This proxy would be alive for TTL time (600 sec by default).
After that you could limit it by `http://localhost:9090/proxy/[port-number]/limit`

**Comment by roydekleijn** [comment]
The application is a spring-boot application... Do I need to start it with proxy host and port?

All I want to do is manipulate the networktraffic (latency/etc) when invoking my rest-application.  <docker-machine-ip:8080>


I start my application, like this:
ENTRYPOINT ["java","-Dhttp.proxyHost 192.168.99.100 -Dhttp.proxyPort=39500”,”-jar","/rest-application.jar"]

I try to add latency, like this:
POST: http://192.168.99.100:9090/proxy

PUT: http://192.168.99.100:9090/proxy/39500/limit?latency=500


Am I missing something ?

**Comment by QAutomatron** [comment]
I think you should start BMP first. But you should be aware of TTL timeout so you created proxy will alive. You could increase it, or set to 0, i think 0 is off.
Then you open proxy port and set latency, as you mention above (POST will create port and tell you the number, /limit will set parameters you want)
After that you should start you app and set it to use your new created port as proxy. After that you app will use proxy with custom latency.

**Comment by roydekleijn** [comment]
Can I add you to skype ? so, I can elaborate a bit more on this topic

**Comment by QAutomatron** [comment]
It seems that you need more info about how BMP work, than how to use it inside docker. So i think you'll can get more information if you post your situation at https://github.com/lightbody/browsermob-proxy/issues 
Current repo is just a wrap for BMP to run as Docker container, and to expose most used parameters. And as for me i used it only as basic proxy without using additional functions, everything that i know i get from BMP manual page.
